# Bag of words 3 april

In [15]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

## Text cleaning, stemming, stopwords removing

In [20]:
import re
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize
lm = WordNetLemmatizer()
corpus = []
sentences = sent_tokenize(paragraph)
for sentence in sentences:
    review = re.sub(r'[^a-zA-Z.]+',' ', sentence).lower()
    review = review.split()
    review = [lm.lemmatize(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

corpus

['three vision india.',
 'year history people world come invaded u captured land conquered minds.',
 'alexander onwards greek turk mogul portuguese british french dutch came looted u took ours.',
 'yet done nation.',
 'conquered anyone.',
 'grabbed land culture history tried enforce way life them.',
 '',
 'respect freedom others.that first vision freedom.',
 'believe india got first vision started war independence.',
 'freedom must protect nurture build on.',
 'free one respect us.',
 'second vision india development.',
 'fifty year developing nation.',
 'time see developed nation.',
 'among top nation world term gdp.',
 'percent growth rate areas.',
 'poverty level falling.',
 'achievement globally recognised today.',
 'yet lack self confidence see developed nation self reliant self assured.',
 'incorrect',
 'third vision.',
 'india must stand world.',
 'believe unless india stand world one respect us.',
 'strength respect strength.',
 'must strong military power also economic power.'

### Applying Bag of Words

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

### Applying Tf-Idf

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer()
X_tf = tf.fit_transform(corpus).toarray()
X_tf

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.25883507, 0.30512561,
        0.        ],
       [0.        , 0.2773501 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

### Word2Vec

In [31]:
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize
new_corpus = [word_tokenize(sentence) for sentence in corpus]
# Training the Word2Vec model
model = Word2Vec(new_corpus, min_count=1)
#if the word is present < then 1 then use to skip the  conunt and as my data is very small 
#word2vec is applied for huge amount of data

In [35]:
# Finding Word Vectors
vector = model.wv['war']
#if i want to find the vector of war word and if i want to find the relationship 
vector

array([-0.00778156, -0.0067647 , -0.00314586,  0.00661998, -0.00083862,
        0.00885579, -0.0022869 , -0.00527606,  0.00391204,  0.00219418,
       -0.00028644, -0.00247473, -0.00601351,  0.0040706 , -0.00761856,
       -0.00891593, -0.00915735,  0.00838806,  0.00399032,  0.00709481,
        0.00991447, -0.00722987,  0.00404161,  0.00280477,  0.00616385,
       -0.003396  ,  0.00931382, -0.00580054,  0.00703017,  0.00694239,
       -0.00038915,  0.00506917,  0.00667078,  0.00151696,  0.00735391,
        0.00241414, -0.00150715,  0.00740738,  0.00469352, -0.0031889 ,
        0.00166394, -0.0001386 ,  0.00495837, -0.00543187, -0.00416714,
       -0.00092253,  0.00380693, -0.00657267,  0.0078624 , -0.00308292,
        0.0057371 ,  0.00283747,  0.00682438, -0.0044562 , -0.00321379,
        0.00306628, -0.00277081,  0.00593644, -0.00595266,  0.00259767,
       -0.00070224, -0.00061544,  0.00252959, -0.00218281, -0.00424451,
       -0.00855882,  0.00247926,  0.00534004, -0.00588124,  0.00

In [36]:
# Most similar words
model.wv.most_similar('war')
#if i try to find most similar word related to the war 

[('brahm', 0.23387396335601807),
 ('dhawan', 0.21503275632858276),
 ('term', 0.21360917389392853),
 ('must', 0.19552014768123627),
 ('incorrect', 0.15426145493984222),
 ('french', 0.13639995455741882),
 ('among', 0.12909086048603058),
 ('dr.', 0.12036918103694916),
 ('four', 0.10741925239562988),
 ('prakash', 0.10618045926094055)]

In [38]:
model.wv.most_similar('freedom')

[('build', 0.2688697874546051),
 ('confidence', 0.20910266041755676),
 ('developing', 0.1775529682636261),
 ('vikram', 0.1541260927915573),
 ('invaded', 0.1430463194847107),
 ('career', 0.130289688706398),
 ('strength', 0.12817755341529846),
 ('recognised', 0.12560154497623444),
 ('lack', 0.11839273571968079),
 ('areas', 0.11378474533557892)]

In [40]:
model.wv.most_similar('vikram')

[('recognised', 0.29878243803977966),
 ('us', 0.18266820907592773),
 ('fifty', 0.15772563219070435),
 ('freedom', 0.1541261225938797),
 ('british', 0.14964725077152252),
 ('great', 0.14674432575702667),
 ('growth', 0.14438821375370026),
 ('professor', 0.13428857922554016),
 ('go', 0.13385987281799316),
 ('invaded', 0.12830732762813568)]